name: Kashmir CI

on:
  push:
    branches: [v2]
  pull_request:
    branches: [v2]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install
        run: yarn install
      - name: Test
        run: |
          yarn gulp
